packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  '@whiskeysockets/baileys': false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: false
  puppeteer: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@whiskeysockets/baileys'
  - protobufjs
  - puppeteer
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/client'
  - '@prisma/engines'

overrides:
  ioredis: 5.11.1

packageExtensions:
  '@whiskeysockets/baileys@7.0.0-rc13':
    peerDependenciesMeta:
      sharp:
        optional: true
patchedDependencies:
  libsignal@6.0.0: patches/libsignal@6.0.0.patch

verifyDepsBeforeRun: false
